.coveragerc, lucid/__init__.py, lucid/main_window.py, tests/test_main_window.py
PR #1 !!! 🎉 
This is the first draft of the window management system for the L2S-I home screens. The idea is there is a central view (or multiple views), these will have buttons that launch detailed screens in the right half of the window. By using the `QDockWidget` setup I can drag these docks around, re-attach them e.t.c
The other thing I was pondering for a while was how a child of a child of a child of widget was going to make sure they could expand something in the dock system. What I came up with (with help from @ZLLentz) is that you could traverse backwards up your parent tree and find the closest`LucidMainWindow`. This means that we could live in a world in which we have multiple main windows open and everything still works. The classmethods `LucidMainWindow.find_window` and …
=> LucidMainWindow

.travis.yml, conda-recipe/meta.yaml, dev-requirements.txt, example.py, lucid/main_window.py, lucid/overview.py, lucid/utils.py, requirements.txt, run_tests.py, tests/conftest.py, tests/test_main_window.py, tests/test_overview.py, tests/test_utils.py
Rough branch of the alarm grid system as informed from `happi`
Considerations before merging:
* This branch depends on an older version of the docking system and added an annoying extension to get the "title" of the window. Later this was re-factored to simply set the `objectName` of the widget you pass through
* This branch adds a hook to the API that gives you a slot to fire whenever the widget is closed. This allows us to mark the background of the indicator grid when something has an window open. The idea would be this hook would eventually mark whatever the overview block diagram has a well
* This branch uses `eventFilter` rather heavily. This should be factored out.
=> Alarm Grid

lucid/main_window.py, lucid/overview.py, tests/test_main_window.py
Most of this work I did yesterday while learning more about the PyQtAds and about lucid as well..
So feel free to chime in with the comments, suggestions and what not...
A couple of changes that I did here and points for discussion:
- Why not make the LucidMainWindow a singleton? (I know that some people hate it)...
- Somehow the args were not being passed to the wrapper of `in_dock`, this way it is but it seems wrong...
- I need to remove the `self.dock_area` which is unused...
=> FIX & ENH: Docking fix work

conda-recipe/meta.yaml, lucid/__init__.py, lucid/launcher.py, lucid/main_window.py, lucid/overview.py, lucid/utils.py, requirements.txt
Reminiscent of OSX's settings search, this adds a fuzzy finder that looks through cell names + device names to determine how a highlighting overlay is drawn. For example:
Drop-down examples:
Working on:
TODO / bugfix
=> ENH: highlight cell that matches text

lucid/launcher.py, lucid/utils.py, tests/test_utils.py
Description
-----------
Without setting lazy_wait_for_connection=False a device that has components which are classified as lazy will result in a blocking call when we try to read the configuration_attrs and other information as well.
Since on the UI we need to have the asynchronous behavior of the connection, which is different at an interactive shell usage, it is in our best interest to patch the Device class to have lazy_wait_for_connection=False by default. That allows us to introspect the inner components and assemble the screen as well as subscribe to callback for proper generation of the UI when this device and its signals connect.
This PR supersedes https://github.com/pcdshub/typhos/pull/234
=> ENH: Context Manager to  force ophyd.Device to lazy_wait_for_connection=False

lucid/main_window.py
Before the fix:
After the fix:
=> FIX: Address issue with search dialog when running over X forwarding.

lucid/main_window.py
PyQtAds (all versions, including the latest unreleased 3.2.1) has a bug on Linux causing a segfault when floating any widget.
As this severely impacts functionality on Linux (our target platform), we're working to get this resolved in the upstream Qt-Advanced-Docking-System sooner rather than later. This temporary patch will then be removed.
=> TMP: a temporary patch for disabling floating on Linux

lucid/launcher.py, lucid/overview.py
With exception of the sections missing zero padding, all now is back on alphabetical order.
The issue was due to the fact that cols and rows without devices were not generating a group.
Now we make sure that the groups are created even if no items are available for a particular combination.
Also taking the opportunity to silence the SPAM logger from pyPDB that was generating parser messages like crazy.
Closes https://github.com/pcdshub/lucid/issues/35 and https://github.com/pcdshub/lucid/issues/34
=> FIX: Ensure that grid cols and rows are in alphabetical order

lucid/launcher.py
Closes #11 
This was tested locally with a couple of cases that would clearly break the launcher and it is working.
=> ENH: Install exceptionhook handler to avoid crashs at launcher.

lucid/launcher.py, lucid/main_window.py, lucid/overview.py
FIX: Fixed some issues at the happi loader that were not being taken care of before.
Closes #47 and #11 
Depends on https://github.com/slaclab/pydm/pull/601
Now the UI will present the user with a dialog showing the error and a stacktrace even if no devices were found.
Attn. @ZLLentz and @rajanplumley
=> REF: Refactored the excepthook and improved error handling.

lucid/main_window.py
Closes #38 
For reference: https://stackoverflow.com/questions/48087904/popup-window-grabs-focus-even-when-windowdoesnotacceptfocus-has-been-set
=> FIX: Ensure SearchDialog uses BypassWIndowManagerHint.

lucid/main_window.py
Reverts pcdshub/lucid#27
Based on fix from https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/pull/126
=> Revert "TMP: a temporary patch for disabling floating on Linux"

lucid/launcher.py, lucid/main_window.py, lucid/overview.py
Closes #57 
With the fixes here the grid will no longer be covered by opening a screen of by the toolbar.
I will submit some more fixes to the toolbar in a separated commit to make sure that it does not take too much space of the screen if many items are added into it.
Initial display size with a toolbar:
=> FIX: Adjust lucid initial size.

lucid/splash.py
Closes #79 
I opted for a noop on the timeout method vs changing the class attribute with the timeout.
Please let me know what you think.
=> FIX: Set handle_timeout to noop for Splash screen loading widget.

lucid/overview.py
While this PR does not completely fix the issue for remote workers reported at #57 it helps to visualize the whole grid and allow users to access the buttons at the Quick Launch toolbar.
I tested it with my computer setting the resolution to the worst possible and it fits now.
Here is the screen with the default resolution for my monitor:
And here it is with the lower resolution possible (1152x720):
=> FIX: Try to compact LUCID main screen

lucid/main_window.py
Closes #92 
Apparently no one has been using the search feature for over a year... which is a bit sad!
(`SearchResults` was introduced in https://github.com/pcdshub/happi/releases/tag/v1.5.0)
Also an indicator of inadequate tests in lucid, but 🤷‍♂️
=> FIX: searching for happi devices was broken (SearchResults refactor)

.travis.yml, lucid/launcher.py, lucid/utils.py
I couldn't help but wonder how the new alarm functionality looked in typhos with https://github.com/pcdshub/typhos/pull/441
The answer is that it looks great! See the following view of RIX from psbuild in the grid:
which is an accurate reflection of the alarm state:
is similarly correctly determined:
And the tooltips are fantastic.
Closes #86 (and steals a bit of Zach's thunder)
Supersedes #89 
Back-compat with the previous implementation may be unnecessary. If you feel strongly one way or another, I'd happily modify this PR.
If we decide to remove backward-compatibility of typhos, I'll adjust the version pin once the relevant PR is in and typhos is tagged. Otherwise, LUCID can be tagged/released independently.
=> ENH: use AlarmCircle, if available

.pre-commit-config.yaml, conda-recipe/meta.yaml, lucid/launcher.py, lucid/main_window.py, lucid/utils.py, requirements.txt
Features
-----
* Adds `pre-commit` config
* Enables centralized logging (picks up `pcdsutils` dependency)
* Takes screenshots of visible windows when an exception happens, recording the screenshot ID along with the log message
Notes
------
* Screenshots not working over X forwarding, not sure if I'm doing something wrong or if that's to be expected.
* Ultimately I think a general version of this could go in typhos, but it's not as easy to generalize as (e.g.) the recent documentation widget config
=> ENH: centralized logging with screenshots

.travis.yml, lucid/launcher.py
Only list devices with active=True metadata tags.  
closes #101 
Doesn't really solve a more general problem (specifying device filter settings generically), but it does solve this problem
Interactively
Issue and this PR
=> BUG: only list active devices on launch

lucid/launcher.py
TMO was complaining about their typhos screens launched from lucid not being quite right. The enum value selection on some of the state devices would often come up with no options at all.
It looked similar to issues we saw in lightpath so I decided to boost the EpicsSignal timeouts for the application, like we did in lightpath. This does fix the issue and you can make the issue worse (more devices effected) if you drop the timeout to be arbitrarily low.
This probably shouldn't be the final form of this PR- I think timeout should be configurable, right? I'm not sure if it's best as a cli arg as part of the toolbar yaml or somewhere else. This is a reasonable band-aid though.
REF https://jira.slac.stanford.edu/browse/LCLSECSD-1659
=> MAINT: increase the default timeout to help TMO load properly

lucid/utils.py
The python 3.10 test suite fails on addWidget receiving floats.
This is my code golf submission for resolving it.
The floor division is appropriate and maintains the same layout behavior on both 3.9 and 3.10.
Regardless of this PR, lucid can't quite be run on python 3.10 yet. See https://github.com/pcdshub/pcds-envs/issues/205#issuecomment-1318976830
=> MAINT: make sure we pass ints to addWidget for python 3.10

lucid/launcher.py
adds `--skip_happi` flag to the `lucid` cli, defaulting to false.  Allows `lucid` to be used for just the toolbar, rather than the grid of devices.
closes #116 
interactively
=> ENH: add --skip_happi flag

conda-recipe/meta.yaml, lucid/launcher.py, lucid/main_window.py, requirements.txt
I expect this to fail for pip, which still has pyqtads=3.8.1 as its most recent version (Assuming 4.0.0 changed the module naming, but release notes were less than helpful)
=> MNT: rename QtAds submodule to ads

conda-recipe/meta.yaml, lucid/launcher.py, requirements.txt
Ignore (demote) one specific pydm at-exit error log, and opt in to future extensions to that demoter.
In the pcds-5.8.0 environment, enough qt details have changed that we now get a bunch of spammy error messages at application close. I've yet to be able to figure out a fix for this, so I think a prudent approach is to filter the log messages from ERROR to DEBUG.
This is a companion to https://github.com/pcdshub/pcdsutils/pull/81
=> ENH: apply the new filter from pcdsutils

demo/db.json, lucid/launcher.py
In launcher.py change the beamline argument to a list.
e.g. load beamline K3 for TXI: lucid K3
e.g. load beamline K3 and TXI: lucid K3 TXI
We should actually not use TXI as a beamline?
Tested by launching a screen using `lucid K3` and `lucid K3 TXI`
=> Multi beamline
